### PR TITLE
add:崩铁实时便笺阈值提醒

### LINKED ISSUE #140: 星穹铁道的便笺
后续有计划做星穹铁道的便笺吗？我尝试自己去添加，结果返回的内容是
```
07-17 15:38:25 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"invalid request","retcode":-10001}
``` 
我添加了
```
URL_STARRAIL_STATUS_BBS = "https://api-takumi-record.mihoyo.com/game_record/app/hkrpg/api/note"
URL_STARRAIL_STATUS_WIDGET = "https://api-takumi-record.mihoyo.com/game_record/app/hkrpg/aapi/widget"

async def StarRail_board(account: UserAccount) -> Tuple[
    Union[BaseApiStatus, StarRailBoardStatus], Optional[StarRailBoard]]:
    """
    获取星铁实时便笺

    :param account: 用户账户数据
    """
    game_record_status, records = await get_game_record(account)
    if not game_record_status:
        return game_record_status, None
    game_list_status, game_list = await get_game_list()
    if not game_list_status:
        return game_list_status, None
    game_filter = filter(lambda x: x.en_name == 'sr', game_list)
    game_info = next(game_filter, None)
    if not game_info:
        return StarRailBoardStatus(no_starrail_account=True), None
    else:
        game_id = game_info.id
    flag = True
    for record in records:
        if record.game_id == game_id:
            try:
                flag = False
                params = {"role_id": record.game_role_id, "server": record.region}
                print("params:",params)
                url = f"{URL_STARRAIL_STATUS_BBS}?{urlencode(params)}"
                print(url)
                headers = HEADERS_STARRAIL_STATUS_BBS.copy()
                headers["x-rpc-device_id"] = account.device_id_android
                async for attempt in get_async_retry(False):
                    with attempt:
                        headers["DS"] = generate_ds(
                            params={"role_id": record.game_role_id, "server": record.region})
                        print(headers)
                        async with httpx.AsyncClient() as client:
                            res = await client.get(url, headers=headers,
                                                   cookies=account.cookies.dict(v2_stoken=True, cookie_type=True),
                                                   timeout=_conf.preference.timeout)
                        api_result = ApiResultHandler(res.json())
                        print("第一次：",api_result)
                        if api_result.login_expired:
                            logger.info(
                                f"星铁实时便笺: 用户 {account.bbs_uid} 登录失效")
                            logger.debug(f"网络请求返回: {res.text}")
                            return StarRailBoardStatus(login_expired=True), None

                        if api_result.invalid_ds:
                            logger.info(
                                f"星铁实时便笺: 用户 {account.bbs_uid} DS 校验失败")
                            logger.debug(f"网络请求返回: {res.text}")
                        if api_result.retcode == 1034:
                            logger.info(
                                f"星铁实时便笺: 用户 {account.bbs_uid} 可能被验证码阻拦")
                            logger.debug(f"网络请求返回: {res.text}")
                        if api_result.invalid_ds or api_result.retcode == 1034:
                            headers["DS"] = generate_ds()
                            headers["x-rpc-device_id"] = account.device_id_ios
                            async with httpx.AsyncClient() as client:
                                res = await client.get(
                                    URL_STARRAIL_STATUS_WIDGET,
                                    headers=headers,
                                    cookies=account.cookies.dict(v2_stoken=True, cookie_type=True),
                                    timeout=_conf.preference.timeout
                                )
                            print("请求返回：",res)
                            api_result = ApiResultHandler(res.json())
                            print("第二次：",api_result)
                            return StarRailBoardStatus(success=True), \
                                StarRailBoard.parse_obj(api_result.data)
                        return StarRailBoardStatus(success=True), StarRailBoard.parse_obj(api_result.data)
            except tenacity.RetryError as e:
                if is_incorrect_return(e):
                    logger.exception(f"星铁实时便笺: 服务器没有正确返回")
                    logger.debug(f"网络请求返回: {res.text}")
                    return StarRailBoardStatus(incorrect_return=True), None
                else:
                    logger.exception(f"星铁实时便笺: 请求失败")
                    return StarRailBoardStatus(network_error=True), None
    if flag:
        return StarRailBoardStatus(no_starrail_account=True), None
``` 
game_list和game_records都成功返回内容，但是倒在了这里
```
async with httpx.AsyncClient() as client:
                            res = await client.get(url, headers=headers,
                                                   cookies=account.cookies.dict(v2_stoken=True, cookie_type=True),
                                                   timeout=_conf.preference.timeout)
                        api_result = ApiResultHandler(res.json())
``` 
下面是终端上的错误信息
```
07-17 15:38:20 [SUCCESS] nonebot | OneBot V11 3451066253 | [message.private.friend]: Message -892711309 from aaaaaaaa '/便笺sr'
07-17 15:38:20 [DEBUG] nonebot | Checking for matchers in priority 1...
07-17 15:38:20 [DEBUG] nonebot | Checking for matchers in priority 4...
07-17 15:38:20 [DEBUG] nonebot | Checking for matchers in priority 5...
07-17 15:38:20 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mystool.plan)
07-17 15:38:20 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_mystool.plan)
07-17 15:38:20 [TRACE] nonebot | Matcher(type='message', module=nonebot_plugin_mystool.plan) run with incoming args: bot=Bot(type='OneBot V11', self_id='3451066253'), event=PrivateMessageEvent(time=1689579500, self_id=3451066253, post_type='message', sub_type='friend', user_id=aaaaaaaa, message_type='private', message_id=-892711309, message=[MessageSegment(type='text', data={'text': '/便笺sr'})], original_message=[MessageSegment(type='text', data={'text': '/便笺sr'})], raw_message='/便笺sr', font=0, sender=Sender(user_id=aaaaaaaa, nickname='哥', sex='unknown', age=0, card=None, area=None, level=None, role=None, title=None), to_me=True, reply=None, target_id=3451066253), state={'_prefix': {'command': ('便笺sr',), 'raw_command': '/便笺sr', 'command_arg': [], 'command_start': '/', 'command_whitespace': None}}
07-17 15:38:20 [DEBUG] nonebot | Running handler Dependent(call=_)
---params: {'role_id': 'bbbbbbb', 'server': 'prod_gf_cn'}
---https://api-takumi-record.mihoyo.com/game_record/app/hkrpg/api/note?role_id=bbbbbbb&server=prod_gf_cn
---{'DS': '1689579501,193865,3b4a00e9fef2b03514d8e315646212d6', 'x-rpc-device_id': 'F9235676-FBF4-46E5-BB9E-A9330E0FDC88', 'Accept': 'application/json,text/plain,*/*', 'Origin': 'https://webstatic.mihoyo.com', 'User-agent': 'Mozilla/5.0 (Linux; Android 11; MI 8 SE Build/RQ3A.211001.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36 miHoYoBBS/2.36.1', 'Referer': 'https://webstatic.mihoyo.com/', 'x-rpc-app_version': '2.28.1', 'x-rpc-channel': 'ys', 'X-Requested-With': 'com.mihoyo.hyperion', 'x-rpc-client_type': '5'}
---第一次： content={'data': None, 'message': '', 'retcode': 1034} data=None message=None retcode=1034
07-17 15:38:22 [INFO] nonebot_plugin_mystool | 星铁实时便笺: 用户 76454149 可能被验证码阻拦
07-17 15:38:22 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"","retcode":1034}
---请求返回： <Response [200 OK]>
---第二次： content={'data': None, 'message': 'invalid request', 'retcode': -10001} data=None message='invalid request' retcode=-10001
07-17 15:38:24 [ERROR] nonebot_plugin_mystool | 星铁实时便笺: 服务器没有正确返回
Traceback (most recent call last):
  File "pydantic\main.py", line 522, in pydantic.main.BaseModel.parse_obj
    obj = dict(obj)
TypeError: 'NoneType' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\site-packages\nonebot_plugin_mystool\simple_api.py", line 1475, in StarRail_board
    StarRailBoard.parse_obj(api_result.data)
  File "pydantic\main.py", line 525, in pydantic.main.BaseModel.parse_obj
    raise ValidationError([ErrorWrapper(exc, loc=ROOT_KEY)], cls) from e
pydantic.error_wrappers.ValidationError: 1 validation error for StarRailBoard
__root__
  StarRailBoard expected dict not NoneType (type=type_error)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\site-packages\nonebot\message.py", line 467, in check_and_run_matcher
    await _run_matcher(
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\site-packages\nonebot\message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\site-packages\nonebot\internal\matcher\matcher.py", line 728, in simple_run
    await handler(
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\site-packages\nonebot_plugin_mystool\plan.py", line 102, in _
    await resin_check_sr(bot=bot, qq=event.user_id, is_auto=False, group_event=event)
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\site-packages\nonebot_plugin_mystool\plan.py", line 462, in resin_check_sr
    starrail_board_status, board = await StarRail_board(account)
> File "C:\ProgramData\anaconda3\envs\mhy\Lib\site-packages\nonebot_plugin_mystool\simple_api.py", line 1436, in StarRail_board
    async for attempt in get_async_retry(False):
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\site-packages\tenacity\_asyncio.py", line 71, in __anext__
    do = self.iter(retry_state=self._retry_state)
  File "C:\ProgramData\anaconda3\envs\mhy\Lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1f75acef690 state=finished raised ValidationError>]
07-17 15:38:25 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"invalid request","retcode":-10001}
07-17 15:38:25 [INFO] nonebot_plugin_mystool | success=False network_error=False incorrect_return=True login_expired=False need_verify=False invalid_ds=False no_starrail_account=False
07-17 15:38:25 [DEBUG] nonebot | OneBot V11 | Calling API send_private_msg
07-17 15:38:26 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mystool.plan) running complete
07-17 15:38:26 [DEBUG] nonebot | Stop event propagation
07-17 15:38:26 [DEBUG] nonebot | Checking for matchers completed
```

### PR DESCRIPTION
**Pull request by dontdot**
自动时：达到开拓力设置的阈值后才会开始推送消息

### CODE REVIEW

**Comment by dontdot** [comment]
plugin_data.json是怎么自动生成的，是会自动加上stamina_threshold的吗

**Comment by Ljzd-PRO** [comment]
> plugin_data.json是怎么自动生成的，是会自动加上stamina_threshold的吗

用的是pydantic来管理数据的。会把python对象序列化成JSON。
在属性里加上stamina_threshold以后，读取的时候就会查找这一项的值，写入的时候也会写入。

**Comment by Ljzd-PRO** [comment]
不过可能类型要指定为`Optional[int]`，这样之前的配置文件没有这一项也可以使用，会读取默认值来用，然后再写入的时候就会加上了

**Comment by Ljzd-PRO** [comment]
Optional的话还不确定到时候读取的时候说读默认值还是读None

**Comment by dontdot** [comment]
这个交给大佬你手动改一下了

**Comment by dontdot** [comment]
突然想到个问题，他这个是全局变量吧，我这样写不可能让每个人设置各自的阈值的

**Comment by Ljzd-PRO** [comment]
> 突然想到个问题，他这个是全局变量吧，我这样写不可能让每个人设置各自的阈值的

对的，偏好设置是插件设置，NoneBot启动前就要设置好。用户设置要写在`UserAccount`里。
https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/27abfa7c5cfa9468f5d1717c812a76e02181fe1c/src/nonebot_plugin_mystool/user_data.py#L198-L228

同时也要在`setting.py`加上

**Comment by dontdot** [comment]
```
@account_setting.got('bbs_uid')
async def _(event: Union[PrivateMessageEvent, GroupMessageEvent], matcher: Matcher, state: T_State, uid=Arg('bbs_uid')):
    """
    根据手机号设置相应的账户
    """
    if isinstance(uid, Message):
        uid = uid.extract_plain_text().strip()
    if uid == '退出':
        await matcher.finish('🚪已成功退出')

    user_account = _conf.users[event.user_id].accounts
    if uid not in user_account:
        await account_setting.reject('⚠️您发送的账号不在以上账号内，请重新发送')
    account = user_account[uid]
    state['account'] = account
    state["prepare_to_delete"] = False

    user_setting = ""
    user_setting += f"1️⃣ 米游币任务自动执行：{'开' if account.enable_mission else '关'}"
    user_setting += f"\n2️⃣ 游戏自动签到：{'开' if account.enable_game_sign else '关'}"
    platform_show = "iOS" if account.platform == "ios" else "安卓"
    user_setting += f"\n3️⃣ 设备平台：{platform_show}"

    # 筛选出用户数据中的missionGame对应的游戏全称
    user_setting += "\n\n4️⃣ 执行米游币任务的频道：" + \
                    "\n- " + "、".join(map(lambda x: f"『{x.NAME}』", account.mission_games))
    user_setting += f"\n\n5️⃣ 原神树脂恢复提醒：{'开' if account.enable_resin else '关'}"
    user_setting += f"\n6️⃣更改崩铁便笺开拓力提醒阈值 \
                            当前提醒阈值：{account.user_stamina_threshold}"
    user_setting += "\n7️⃣⚠️删除账户数据"

    await account_setting.send(user_setting + '\n\n您要更改哪一项呢？请发送 1 / 2 / 3 / 4 / 5 / 6 / 7'
                                              '\n🚪发送“退出”即可退出')


@account_setting.got('arg')
async def _(event: Union[PrivateMessageEvent, GroupMessageEvent], state: T_State, arg=ArgPlainText('arg')):
    """
    根据所选更改相应账户的相应设置
    """
    arg = arg.strip()
    account: UserAccount = state['account']
    user_account = _conf.users[event.user_id].accounts
    if arg == '退出':
        await account_setting.finish('🚪已成功退出')
    elif arg == '1':
        account.enable_mission = not account.enable_mission
        write_plugin_data()
        await account_setting.finish(f"📅米游币任务自动执行已 {'✅开启' if account.enable_mission else '❌关闭'}")
    elif arg == '2':
        account.enable_game_sign = not account.enable_game_sign
        write_plugin_data()
        await account_setting.finish(f"📅米哈游游戏自动签到已 {'✅开启' if account.enable_game_sign else '❌关闭'}")
    elif arg == '3':
        if account.platform == "ios":
            account.platform = "android"
            platform_show = "安卓"
        else:
            account.platform = "ios"
            platform_show = "iOS"
        write_plugin_data()
        await account_setting.finish(f"📲设备平台已更改为 {platform_show}")
    elif arg == '4':
        games_show = "、".join(map(lambda x: f"『{x.NAME}』", BaseMission.AVAILABLE_GAMES))
        await account_setting.send(
            "请发送你想要执行米游币任务的频道："
            "\n❕多个频道请用空格分隔，如 “原神 崩坏3 大别野”"
            "\n\n可选的频道："
            f"\n- {games_show}"
            "\n\n🚪发送“退出”即可退出"
        )
    elif arg == '5':
        account.enable_resin = not account.enable_resin
        write_plugin_data()
        await account_setting.finish(f"📅原神树脂恢复提醒已 {'✅开启' if account.enable_resin else '❌关闭'}")
    elif arg == '6':
        await account_setting.send(
            "请输入想要所需阈值数字："
            "支持输入[0,180]"
            "\n\n🚪发送“退出”即可退出"
        )
    elif arg == '7':
        state["prepare_to_delete"] = True
        await account_setting.reject(f"⚠️确认删除账号 {account.phone_number} ？发送 \"确认删除\" 以确定。")
    elif arg == '确认删除' and state["prepare_to_delete"]:
        user_account.pop(account.bbs_uid)
        write_plugin_data()
        await account_setting.finish(f"已删除账号 {account.phone_number} 的数据")
    else:
        await account_setting.reject("⚠️您的输入有误，请重新输入")


@account_setting.got('threshold')
async def _(_: Union[PrivateMessageEvent, GroupMessageEvent], state: T_State, arg=ArgPlainText('threshold')):
    arg = arg.strip()
    if arg == '退出':
        await account_setting.finish('🚪已成功退出')
    account: UserAccount = state['account']
    try:
        stamina_threshold = int(arg)
    except ValueError:
        await account_setting.reject("⚠️请输入有效的数字。")
        return

    if 0 <= stamina_threshold <= 180:
        # 输入有效的数字范围，将 stamina_threshold 赋值为输入的整数
        account.user_stamina_threshold = stamina_threshold
        write_plugin_data()
        await account_setting.finish(f"更改崩铁便笺开拓力提醒阈值成功，当前提醒阈值：{stamina_threshold}")
    else:
        await account_setting.reject("⚠️输入的数字范围应在 0 到 180 之间。")



@account_setting.got('missionGame')
async def _(_: Union[PrivateMessageEvent, GroupMessageEvent], state: T_State, arg=ArgPlainText('missionGame')):
    arg = arg.strip()
    if arg == '退出':
        await account_setting.finish('🚪已成功退出')
    account: UserAccount = state['account']
    games_input = arg.split()
    mission_games = set()
    for game in games_input:
        game_filter = filter(lambda x: x.NAME == game, BaseMission.AVAILABLE_GAMES)
        game_obj = next(game_filter, None)
        if game_obj is None:
            await account_setting.reject("⚠️您的输入有误，请重新输入")
        else:
            mission_games.add(game_obj)

    account.mission_games = mission_games
    write_plugin_data()
    arg = arg.replace(" ", "、")
    await account_setting.finish(f"💬执行米游币任务的频道已更改为『{arg}』")
``` 
大佬，我这里就差最后一步了。
setting这里没法区分开
```
'4'触发@account_setting.got('missionGame')
'6'触发@account_setting.got('threshold')
```

**Comment by dontdot** [comment]
> ```
> @account_setting.got('bbs_uid')
> async def _(event: Union[PrivateMessageEvent, GroupMessageEvent], matcher: Matcher, state: T_State, uid=Arg('bbs_uid')):
>     """
>     根据手机号设置相应的账户
>     """
>     if isinstance(uid, Message):
>         uid = uid.extract_plain_text().strip()
>     if uid == '退出':
>         await matcher.finish('🚪已成功退出')
> 
>     user_account = _conf.users[event.user_id].accounts
>     if uid not in user_account:
>         await account_setting.reject('⚠️您发送的账号不在以上账号内，请重新发送')
>     account = user_account[uid]
>     state['account'] = account
>     state["prepare_to_delete"] = False
> 
>     user_setting = ""
>     user_setting += f"1️⃣ 米游币任务自动执行：{'开' if account.enable_mission else '关'}"
>     user_setting += f"\n2️⃣ 游戏自动签到：{'开' if account.enable_game_sign else '关'}"
>     platform_show = "iOS" if account.platform == "ios" else "安卓"
>     user_setting += f"\n3️⃣ 设备平台：{platform_show}"
> 
>     # 筛选出用户数据中的missionGame对应的游戏全称
>     user_setting += "\n\n4️⃣ 执行米游币任务的频道：" + \
>                     "\n- " + "、".join(map(lambda x: f"『{x.NAME}』", account.mission_games))
>     user_setting += f"\n\n5️⃣ 原神树脂恢复提醒：{'开' if account.enable_resin else '关'}"
>     user_setting += f"\n6️⃣更改崩铁便笺开拓力提醒阈值 \
>                             当前提醒阈值：{account.user_stamina_threshold}"
>     user_setting += "\n7️⃣⚠️删除账户数据"
> 
>     await account_setting.send(user_setting + '\n\n您要更改哪一项呢？请发送 1 / 2 / 3 / 4 / 5 / 6 / 7'
>                                               '\n🚪发送“退出”即可退出')
> 
> 
> @account_setting.got('arg')
> async def _(event: Union[PrivateMessageEvent, GroupMessageEvent], state: T_State, arg=ArgPlainText('arg')):
>     """
>     根据所选更改相应账户的相应设置
>     """
>     arg = arg.strip()
>     account: UserAccount = state['account']
>     user_account = _conf.users[event.user_id].accounts
>     if arg == '退出':
>         await account_setting.finish('🚪已成功退出')
>     elif arg == '1':
>         account.enable_mission = not account.enable_mission
>         write_plugin_data()
>         await account_setting.finish(f"📅米游币任务自动执行已 {'✅开启' if account.enable_mission else '❌关闭'}")
>     elif arg == '2':
>         account.enable_game_sign = not account.enable_game_sign
>         write_plugin_data()
>         await account_setting.finish(f"📅米哈游游戏自动签到已 {'✅开启' if account.enable_game_sign else '❌关闭'}")
>     elif arg == '3':
>         if account.platform == "ios":
>             account.platform = "android"
>             platform_show = "安卓"
>         else:
>             account.platform = "ios"
>             platform_show = "iOS"
>         write_plugin_data()
>         await account_setting.finish(f"📲设备平台已更改为 {platform_show}")
>     elif arg == '4':
>         games_show = "、".join(map(lambda x: f"『{x.NAME}』", BaseMission.AVAILABLE_GAMES))
>         await account_setting.send(
>             "请发送你想要执行米游币任务的频道："
>             "\n❕多个频道请用空格分隔，如 “原神 崩坏3 大别野”"
>             "\n\n可选的频道："
>             f"\n- {games_show}"
>             "\n\n🚪发送“退出”即可退出"
>         )
>     elif arg == '5':
>         account.enable_resin = not account.enable_resin
>         write_plugin_data()
>         await account_setting.finish(f"📅原神树脂恢复提醒已 {'✅开启' if account.enable_resin else '❌关闭'}")
>     elif arg == '6':
>         await account_setting.send(
>             "请输入想要所需阈值数字："
>             "支持输入[0,180]"
>             "\n\n🚪发送“退出”即可退出"
>         )
>     elif arg == '7':
>         state["prepare_to_delete"] = True
>         await account_setting.reject(f"⚠️确认删除账号 {account.phone_number} ？发送 \"确认删除\" 以确定。")
>     elif arg == '确认删除' and state["prepare_to_delete"]:
>         user_account.pop(account.bbs_uid)
>         write_plugin_data()
>         await account_setting.finish(f"已删除账号 {account.phone_number} 的数据")
>     else:
>         await account_setting.reject("⚠️您的输入有误，请重新输入")
> 
> 
> @account_setting.got('threshold')
> async def _(_: Union[PrivateMessageEvent, GroupMessageEvent], state: T_State, arg=ArgPlainText('threshold')):
>     arg = arg.strip()
>     if arg == '退出':
>         await account_setting.finish('🚪已成功退出')
>     account: UserAccount = state['account']
>     try:
>         stamina_threshold = int(arg)
>     except ValueError:
>         await account_setting.reject("⚠️请输入有效的数字。")
>         return
> 
>     if 0 <= stamina_threshold <= 180:
>         # 输入有效的数字范围，将 stamina_threshold 赋值为输入的整数
>         account.user_stamina_threshold = stamina_threshold
>         write_plugin_data()
>         await account_setting.finish(f"更改崩铁便笺开拓力提醒阈值成功，当前提醒阈值：{stamina_threshold}")
>     else:
>         await account_setting.reject("⚠️输入的数字范围应在 0 到 180 之间。")
> 
> 
> 
> @account_setting.got('missionGame')
> async def _(_: Union[PrivateMessageEvent, GroupMessageEvent], state: T_State, arg=ArgPlainText('missionGame')):
>     arg = arg.strip()
>     if arg == '退出':
>         await account_setting.finish('🚪已成功退出')
>     account: UserAccount = state['account']
>     games_input = arg.split()
>     mission_games = set()
>     for game in games_input:
>         game_filter = filter(lambda x: x.NAME == game, BaseMission.AVAILABLE_GAMES)
>         game_obj = next(game_filter, None)
>         if game_obj is None:
>             await account_setting.reject("⚠️您的输入有误，请重新输入")
>         else:
>             mission_games.add(game_obj)
> 
>     account.mission_games = mission_games
>     write_plugin_data()
>     arg = arg.replace(" ", "、")
>     await account_setting.finish(f"💬执行米游币任务的频道已更改为『{arg}』")
> ```
> 
> 大佬，我这里就差最后一步了。 setting这里没法区分开
> 
> ```
> '4'触发@account_setting.got('missionGame')
> '6'触发@account_setting.got('threshold')
> ```

/账号设置 —> 4 —> 触发@account_setting.got('threshold')
/账号设置 —> 6 —> 触发@account_setting.got('threshold')

**Comment by dontdot** [comment]
我没搞懂为什么输入4后会触发account_setting.got('missionGame')，是因为missionGame吗？可是也没定义这个啊

**Comment by Ljzd-PRO** [comment]
大概是因为选择了设置项以后，之前只有`missionGame` 需要进一步接收参数处理，现在加了 `threshold`，两个就区分不开了

**Comment by dontdot** [comment]
> 

我先把弄好的pr上去，大佬你后面看下怎么改可以不，我到这里真搞不懂该这么做了

**Comment by Ljzd-PRO** [comment]
好的

**Comment by Ljzd-PRO** [comment]
应该是解決了，可以测试看看设置功能里提醒阈值和提醒阈值能否正常使用。

**Comment by dontdot** [comment]
> 应该是解決了，可以测试看看设置功能里提醒阈值和提醒阈值能否正常使用。

没问题了

**Pull request merged**
